config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, only: [:show, :new, :create, :index, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create]
  end

  # /spaces/id/bookings/new
  resources :bookings, only: [:show, :update] do
    member do
      patch :approve
      patch :decline
    end
  end




  resources :bookings, only: :destroy

  resource :dashboard, only: [:show]

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :update, :destroy, :approve, :decline]

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new
    @space = Space.find(params[:space_id])
    @booking.user = current_user
    @booking.space = @space
    @booking.total_price = @space.price + 10
    @booking.status = "Pending"
    if @booking.save
      redirect_to spaces_path, notice: "Booking was successfully created."
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  def approve
    @booking.status = 'Approved'
    @booking.save
    redirect_to dashboard_path, notice: 'Booking approved'
  end

  def decline
    @booking.status = 'Declined'
    @booking.save
    redirect_to dashboard_path, notice: 'Booking declined'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end


  # Only allow a trusted parameter "white list" through.
  # def booking_params
  #   params.require(:booking).permit(:status, :total_price)
  # end
end

app/views/bookings/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1495320520040-44186a20c601?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80)">
  <h1>XSpace </h1>
  <h2>ALL BOOKINGS</h2>
</div>

<% @bookings.each do |booking| %>

 <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><strong>Space:</strong> <%= booking.space.name %></h5>
    <p class="card-text"><strong>Status:</strong><%= booking.status %></p>
    <p class="card-text"><strong>Price:</strong><%= booking.total_price %></p>
    <p class="card-text"><strong>Sender: </strong><%= booking.user.name %></p>
    <p class="card-text"><strong>Transporter: </strong><%= booking.space.user.name %></p>
  </div>
</div>

<ul>
  <li><h4>Space: <%= booking.space.name %></h4></li>
  <li><%= booking.status %> </li>
  <li><%= booking.total_price %></li>
  <li>Sender: <%= booking.user.name %></li>
  <li>Transporter: <%= booking.space.user.name %></li>
</ul>
<p><%= link_to 'Show', booking_path(booking) %></p>
<% end %>



<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Spaces</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">bookings</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">...</div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
</div>