config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, only: [:show, :new, :create, :index, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create]
  end

  # /spaces/id/bookings/new
  resources :bookings, only: [:show, :update] do
    member do
      patch :approve
      patch :decline
    end
  end




  resources :bookings, only: :destroy

  resource :dashboard, only: [:show]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-xspace">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "main-logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", spaces_path, class: "nav-link", id:'nav-text' %>
        </li>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link", id:'nav-text' %>
        </li>
        <li class="nav-item active">
          <%= link_to "Add New Space", new_space_path, class: "nav-link", id:'nav-text' %>
        </li>
        <li class="nav-item active">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", id:'nav-text' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", id:'nav-text' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>