config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, only: [:show, :new, :create, :index, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create]
  end

  # /spaces/id/bookings/new
  resources :bookings, only: [:show, :update] do
    member do
      patch :approve
      patch :decline
    end
  end




  resources :bookings, only: :destroy

  resource :dashboard, only: [:show]

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @bookings = current_user.bookings
    @spaces = current_user.spaces
  end
end

app/views/dashboards/show.html.erb
<div class='dashboard-body'>
  <h1>Welcome to your dashboard, <%= current_user.name %> !</h1>
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Bookings</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Spaces</a>
      </li>
    </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <section>
        <div>
          <div class="list-container">
            <% @bookings.each do |booking| %>

                <div class="card ">
                    <div class="title">
                      <h5 class="card-title"><strong>Space: </strong> <%= booking.space.name %></h5>
                    </div>
                    <div class="price">
                      <h4>Price: $<%= booking.total_price %></h4>
                    </div>
                    <div class="option">
                      <ul>
                      <li> </i> Status: <%= booking.status %> </li>
                      <li> </i> Transporter: <%= booking.space.user.name %> </li>
                      <li> </i> <%= booking.space.location %> → <%= booking.space.destination %> </li>
                      </ul>
                    </div>
                  <%= link_to "Cancel Booking", booking, method: :delete, data: { confirm: 'Are you sure you want to cancel your space booking?' }, class:'anchor' %>
                </div>
            <% end %>
          </div>
      </section>
    </div>

    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">

      <div class="card-wrapper">
        <% @spaces.each do |space| %>
          <div class="card-space">

            <div class='card-tools'>
              <%= link_to "🖊", edit_space_path(space), class:'edit' %>
              <%= link_to "🗑", space, method: :delete, data: { confirm: 'Are you sure?' }, class:'delete'%>
            </div>

            <div class='card-info'>

              <% if space.photos.presence %>
                <%= cl_image_tag space.photos.first.key , class:'card-image' %>
              <%else%>
                <img src="https://images.unsplash.com/photo-1448582649076-3981753123b5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8bHVnZ2FnZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60" class="card-image" alt="luggage image">
              <%end%>

              <li class='title'><%= space.name %> </li>
                <div class='dimension'>
                <li class='card-text'><span>From: </span><%= space.location.capitalize %></li>
                <li class='card-text'><span>To: </span><%= space.destination.capitalize %></li>
                </div>
              <li class='card-text'><span>Date: </span><%= space.travel_date.strftime('%d-%m-%Y') %></li>
              <li class='card-text'><span><i class="fas fa-money-bill"></i> </span><%= space.price %> dollars</li>
                <div class='dimension'>
                  <li class='card-text'><span>Height</span> <%= space.height %> cm</li>
                  <li class='card-text'><span>Width</span> <%= space.width %> cm</li>
                  <li class='card-text'><span>Depth</span> <%= space.depth %> cm</li>
                </div>
            </div>

                <% if space.booking %>
                  <p class='card-text'><span>Status: </span><%= space.booking.status %></p>
                  <p class='card-text'><span>Booker:</span> <%= space.booking.user.name %></p>
                  <div class='btn-container'>
                    <p><%= link_to "Approve",  approve_booking_path(space.booking), method: :patch, class:'btn-approve btn' %></p>
                    <p><%= link_to "Decline",  decline_booking_path(space.booking), method: :patch, class:'btn-decline btn' %></p>
                  </div>
                <% else %>
                  <p class='card-text'><span>Status: </span>Free to book</p>
                <% end %>
              <%= link_to 'Show', space_path(space), class: 'btn-wide' %>
          </div>
        <%end%>
      </div>
    </div>
  <div>
</div>